CRITICAL - 2021-04-02 08:48:01 --> Undefined index: foto
#0 C:\xampp\htdocs\cs\app\Controllers\Auth.php(58): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'C:\\xampp\\htdocs...', 58, Array)
#1 C:\xampp\htdocs\cs\system\CodeIgniter.php(936): App\Controllers\Auth->authenticate()
#2 C:\xampp\htdocs\cs\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\cs\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\cs\public\index.php(44): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-04-02 11:00:20 --> Undefined index: foto
#0 C:\xampp\htdocs\cs\app\Controllers\Auth.php(58): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'C:\\xampp\\htdocs...', 58, Array)
#1 C:\xampp\htdocs\cs\system\CodeIgniter.php(936): App\Controllers\Auth->authenticate()
#2 C:\xampp\htdocs\cs\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\cs\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\cs\public\index.php(44): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-04-02 13:44:47 --> Undefined index: foto
#0 C:\xampp\htdocs\cs\app\Controllers\Auth.php(58): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'C:\\xampp\\htdocs...', 58, Array)
#1 C:\xampp\htdocs\cs\system\CodeIgniter.php(936): App\Controllers\Auth->authenticate()
#2 C:\xampp\htdocs\cs\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\cs\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\cs\public\index.php(44): CodeIgniter\CodeIgniter->run()
#5 {main}
ERROR - 2021-04-02 17:11:37 --> Error connecting to the database: MySQL server has gone away
CRITICAL - 2021-04-02 17:11:37 --> Unable to connect to the database.
#0 C:\xampp\htdocs\cs\system\Database\BaseConnection.php(618): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\cs\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\cs\app\Models\Querys.php(32): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\cs\app\Helpers\SanPedro_helper.php(10): App\Models\Querys->verifyUser(Array)
#4 C:\xampp\htdocs\cs\app\Controllers\BaseController.php(56): authenticated()
#5 C:\xampp\htdocs\cs\system\CodeIgniter.php(909): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#6 C:\xampp\htdocs\cs\system\CodeIgniter.php(422): CodeIgniter\CodeIgniter->createController()
#7 C:\xampp\htdocs\cs\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\cs\public\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-04-02 19:51:51 --> Undefined index: foto
#0 C:\xampp\htdocs\cs\app\Controllers\Auth.php(58): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'C:\\xampp\\htdocs...', 58, Array)
#1 C:\xampp\htdocs\cs\system\CodeIgniter.php(936): App\Controllers\Auth->authenticate()
#2 C:\xampp\htdocs\cs\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\cs\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\cs\public\index.php(44): CodeIgniter\CodeIgniter->run()
#5 {main}
ERROR - 2021-04-02 19:52:56 --> mysqli_sql_exception: Unknown column 'u.foto' in 'field list' in C:\xampp\htdocs\cs\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\cs\system\Database\MySQLi\Connection.php(314): mysqli->query('SELECT CONCAT(u...')
#1 C:\xampp\htdocs\cs\system\Database\BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT CONCAT(u...')
#2 C:\xampp\htdocs\cs\system\Database\BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT CONCAT(u...')
#3 C:\xampp\htdocs\cs\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT CONCAT(u...', Array, false)
#4 C:\xampp\htdocs\cs\app\Models\PerfilModel.php(52): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\cs\app\Controllers\Perfil.php(26): App\Models\PerfilModel->datos_usuario_perfil('1')
#6 C:\xampp\htdocs\cs\system\CodeIgniter.php(936): App\Controllers\Perfil->datos_usuario()
#7 C:\xampp\htdocs\cs\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Perfil))
#8 C:\xampp\htdocs\cs\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\cs\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-04-02 19:52:56 --> Unknown column 'u.foto' in 'field list'
#0 C:\xampp\htdocs\cs\system\Database\MySQLi\Connection.php(314): mysqli->query('SELECT CONCAT(u...')
#1 C:\xampp\htdocs\cs\system\Database\BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT CONCAT(u...')
#2 C:\xampp\htdocs\cs\system\Database\BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT CONCAT(u...')
#3 C:\xampp\htdocs\cs\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT CONCAT(u...', Array, false)
#4 C:\xampp\htdocs\cs\app\Models\PerfilModel.php(52): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\cs\app\Controllers\Perfil.php(26): App\Models\PerfilModel->datos_usuario_perfil('1')
#6 C:\xampp\htdocs\cs\system\CodeIgniter.php(936): App\Controllers\Perfil->datos_usuario()
#7 C:\xampp\htdocs\cs\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Perfil))
#8 C:\xampp\htdocs\cs\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\cs\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2021-04-02 19:53:27 --> mysqli_sql_exception: Unknown column 'u.foto' in 'field list' in C:\xampp\htdocs\cs\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\cs\system\Database\MySQLi\Connection.php(314): mysqli->query('SELECT CONCAT(u...')
#1 C:\xampp\htdocs\cs\system\Database\BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT CONCAT(u...')
#2 C:\xampp\htdocs\cs\system\Database\BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT CONCAT(u...')
#3 C:\xampp\htdocs\cs\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT CONCAT(u...', Array, false)
#4 C:\xampp\htdocs\cs\app\Models\PerfilModel.php(52): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\cs\app\Controllers\Perfil.php(26): App\Models\PerfilModel->datos_usuario_perfil('1')
#6 C:\xampp\htdocs\cs\system\CodeIgniter.php(936): App\Controllers\Perfil->datos_usuario()
#7 C:\xampp\htdocs\cs\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Perfil))
#8 C:\xampp\htdocs\cs\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\cs\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-04-02 19:53:27 --> Unknown column 'u.foto' in 'field list'
#0 C:\xampp\htdocs\cs\system\Database\MySQLi\Connection.php(314): mysqli->query('SELECT CONCAT(u...')
#1 C:\xampp\htdocs\cs\system\Database\BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT CONCAT(u...')
#2 C:\xampp\htdocs\cs\system\Database\BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT CONCAT(u...')
#3 C:\xampp\htdocs\cs\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT CONCAT(u...', Array, false)
#4 C:\xampp\htdocs\cs\app\Models\PerfilModel.php(52): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\cs\app\Controllers\Perfil.php(26): App\Models\PerfilModel->datos_usuario_perfil('1')
#6 C:\xampp\htdocs\cs\system\CodeIgniter.php(936): App\Controllers\Perfil->datos_usuario()
#7 C:\xampp\htdocs\cs\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Perfil))
#8 C:\xampp\htdocs\cs\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\cs\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
