ERROR - 2021-03-21 14:48:05 --> Error connecting to the database: No connection could be made because the target machine actively refused it.

CRITICAL - 2021-03-21 14:48:05 --> Unable to connect to the database.
#0 C:\xampp\htdocs\cs\system\Database\BaseConnection.php(618): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\cs\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\cs\app\Models\Querys.php(32): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\cs\app\Helpers\SanPedro_helper.php(10): App\Models\Querys->verifyUser(Array)
#4 C:\xampp\htdocs\cs\app\Controllers\BaseController.php(56): authenticated()
#5 C:\xampp\htdocs\cs\system\CodeIgniter.php(909): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#6 C:\xampp\htdocs\cs\system\CodeIgniter.php(422): CodeIgniter\CodeIgniter->createController()
#7 C:\xampp\htdocs\cs\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\cs\public\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-03-21 14:56:05 --> Undefined index: foto
#0 C:\xampp\htdocs\cs\app\Controllers\Auth.php(58): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'C:\\xampp\\htdocs...', 58, Array)
#1 C:\xampp\htdocs\cs\system\CodeIgniter.php(936): App\Controllers\Auth->authenticate()
#2 C:\xampp\htdocs\cs\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\cs\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\cs\public\index.php(44): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-03-21 18:04:07 --> include(../dist/includes/dbcon.php): failed to open stream: No such file or directory
#0 C:\xampp\htdocs\cs\app\Views\cita\index.php(284): CodeIgniter\Debug\Exceptions->errorHandler(2, 'include(../dist...', 'C:\\xampp\\htdocs...', 284, Array)
#1 C:\xampp\htdocs\cs\app\Views\cita\index.php(284): include()
#2 C:\xampp\htdocs\cs\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\cs\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#4 C:\xampp\htdocs\cs\system\Common.php(1217): CodeIgniter\View\View->render('cita/index', Array, true)
#5 C:\xampp\htdocs\cs\app\Libraries\Templater.php(26): view('cita/index', Array)
#6 C:\xampp\htdocs\cs\app\Controllers\Cita.php(24): App\Libraries\Templater->view('cita/index', Array)
#7 C:\xampp\htdocs\cs\system\CodeIgniter.php(936): App\Controllers\Cita->index()
#8 C:\xampp\htdocs\cs\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cita))
#9 C:\xampp\htdocs\cs\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\cs\public\index.php(44): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2021-03-21 18:04:27 --> include(../dist/includes/dbcon.php): failed to open stream: No such file or directory
#0 C:\xampp\htdocs\cs\app\Views\cita\index.php(284): CodeIgniter\Debug\Exceptions->errorHandler(2, 'include(../dist...', 'C:\\xampp\\htdocs...', 284, Array)
#1 C:\xampp\htdocs\cs\app\Views\cita\index.php(284): include()
#2 C:\xampp\htdocs\cs\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\cs\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#4 C:\xampp\htdocs\cs\system\Common.php(1217): CodeIgniter\View\View->render('cita/index', Array, true)
#5 C:\xampp\htdocs\cs\app\Libraries\Templater.php(26): view('cita/index', Array)
#6 C:\xampp\htdocs\cs\app\Controllers\Cita.php(24): App\Libraries\Templater->view('cita/index', Array)
#7 C:\xampp\htdocs\cs\system\CodeIgniter.php(936): App\Controllers\Cita->index()
#8 C:\xampp\htdocs\cs\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cita))
#9 C:\xampp\htdocs\cs\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\cs\public\index.php(44): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2021-03-21 18:06:42 --> Undefined variable: start
#0 C:\xampp\htdocs\cs\app\Views\cita\index.php(285): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 285, Array)
#1 C:\xampp\htdocs\cs\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\cs\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\cs\system\Common.php(1217): CodeIgniter\View\View->render('cita/index', Array, true)
#4 C:\xampp\htdocs\cs\app\Libraries\Templater.php(26): view('cita/index', Array)
#5 C:\xampp\htdocs\cs\app\Controllers\Cita.php(24): App\Libraries\Templater->view('cita/index', Array)
#6 C:\xampp\htdocs\cs\system\CodeIgniter.php(936): App\Controllers\Cita->index()
#7 C:\xampp\htdocs\cs\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cita))
#8 C:\xampp\htdocs\cs\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\cs\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-03-21 18:06:54 --> Undefined variable: start
#0 C:\xampp\htdocs\cs\app\Views\cita\index.php(285): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 285, Array)
#1 C:\xampp\htdocs\cs\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\cs\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\cs\system\Common.php(1217): CodeIgniter\View\View->render('cita/index', Array, true)
#4 C:\xampp\htdocs\cs\app\Libraries\Templater.php(26): view('cita/index', Array)
#5 C:\xampp\htdocs\cs\app\Controllers\Cita.php(24): App\Libraries\Templater->view('cita/index', Array)
#6 C:\xampp\htdocs\cs\system\CodeIgniter.php(936): App\Controllers\Cita->index()
#7 C:\xampp\htdocs\cs\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cita))
#8 C:\xampp\htdocs\cs\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\cs\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-03-21 22:20:41 --> Undefined index: foto
#0 C:\xampp\htdocs\cs\app\Controllers\Auth.php(58): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'C:\\xampp\\htdocs...', 58, Array)
#1 C:\xampp\htdocs\cs\system\CodeIgniter.php(936): App\Controllers\Auth->authenticate()
#2 C:\xampp\htdocs\cs\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\cs\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\cs\public\index.php(44): CodeIgniter\CodeIgniter->run()
#5 {main}
